[package]
name = "we"
version = "0.0.19"
description = "An alternative holochain runtime focused on groups"
authors = [
  "eric@harris-braun.com",
  "matthme@protonmail.com",
  "guillem.cordoba@gmail.com",
]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.6", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha.10", features = [] }
tauri-plugin-deep-link = "0.1"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
futures = "0.3"
log = "0.4.14"
portpicker = "0.1"
thiserror = "1"

bzip2 = { version = "0.4", features = ["static"] }

holochain_client = { git = "https://github.com/holochain/holochain-client-rust", branch = "holochain-0.3.0-beta-dev.8" }
holochain_state = "=0.3.0-beta-dev.8"
holochain_websocket = "0.3.0-beta-dev.3"
holochain = "0.3.0-beta-dev.9"
holochain_types = "=0.3.0-beta-dev.8"
mr_bundle = "0.2"
either = "*"

mime_guess = "2.0.4"

hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }

zip = "0.6"

hc_crud_caps = "0.7"
devhub_types = { git = "https://github.com/holochain/devhub-dnas", rev = "1b1ab2adfb67defd597b4a9a3995cf87bf1e1456" }
appstore_types = { git = "https://github.com/holochain/app-store-dnas", rev = "a671385285b9833305bdee9f2226c9d4d9dd6f4e" }
appstore = { git = "https://github.com/holochain/app-store-dnas", rev = "a671385285b9833305bdee9f2226c9d4d9dd6f4e" }
hc_portal_types = { git = "https://github.com/holochain/portal-dna", rev = "66c846ad8695f16c0cfeefd96106ddc48442aaa8" }
essence_payloads = "0.1"

holochain_launcher_utils = { path = "../crates/holochain_launcher_utils" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
