[package]
name = "we"
version = "0.0.12"
description = "An alternative holochain runtime focused on groups"
authors = [
  "eric@harris-braun.com",
  "matthme@protonmail.com",
  "guillem.cordoba@gmail.com",
]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["cli", "clipboard-write-text", "http-all", "protocol-all", "shell-open"] }
tauri-plugin-deep-link = "0.1"

anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
log = "0.4.14"
portpicker = "0.1"
tempdir = "0.3.7"
thiserror = "1"

holochain_client = "0.3.1"
holochain_state = "0.1.3"
holochain_manager = { git = "https://github.com/holochain/launcher", branch = "we" }
holochain_web_app_manager = { git = "https://github.com/holochain/launcher", branch = "we" }
lair_keystore_manager = { git = "https://github.com/holochain/launcher", branch = "we" }
holochain_launcher_utils = { git = "https://github.com/holochain/launcher", branch = "we" }
holochain_types = "0.1.3"
hdk = "0.1"

zip = "0.5"

devhub_types = { git = "https://github.com/holochain/devhub-dnas", branch = "master" }
essence_payloads = "0.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
