[package]
name = "we"
version = "0.0.19"
description = "An alternative holochain runtime focused on groups"
authors = [
  "eric@harris-braun.com",
  "matthme@protonmail.com",
  "guillem.cordoba@gmail.com",
]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.6", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha.10", features = [] }

anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
serde_json = "1.0"
futures = "0.3"
log = "0.4.14"
portpicker = "0.1"
tempdir = "0.3.7"
thiserror = "1"

holochain_client = "0.3.1"
holochain_state = "=0.1.3"
holochain_websocket = "0.1"
holochain = "0.1.3"
holochain_types = "=0.1.3"
hdk = "0.1"
holochain_zome_types = "=0.1.1"
mr_bundle = "0.1"
sodoken = "=0.0.7"
either = "*"

mime_guess = "2.0.4"

hyper = { version = "1.0.0-rc.3", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1.0-rc.2"
bytes = "1"

zip = "0.5"

hc_crud_caps = { git = "https://github.com/mjbrisebois/rust-hc-crud-caps.git", rev = "59752c8aad95bfe421f259a3b2a1cd547dd64457" }
devhub_types = { git = "https://github.com/holochain/devhub-dnas", rev = "10faff9c57af369f353330355eec5e0dac1c8f5d" }
appstore_types = { git = "https://github.com/holochain/app-store-dnas", rev = "a2dc60c80ddb1f82ae28817e6f9bca3416271b1d" }
appstore = { git = "https://github.com/holochain/app-store-dnas", rev = "a2dc60c80ddb1f82ae28817e6f9bca3416271b1d" }
hc_portal_types = { git = "https://github.com/holochain/portal-dna", rev = "4c2075ec54349f9d6a4e2de84d7846282a0938fd" }
essence_payloads = "0.1"

holochain_launcher_utils = { path = "../crates/holochain_launcher_utils" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
