[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "peer_status_coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "peer_status_coordinator"

[dependencies]
hc_zome_peer_status_coordinator = {git = "https://github.com/holochain-open-dev/peer-status", rev = "for-hdk-v0.0.142", package = "hc_zome_peer_status_coordinator"}
