[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "peer_status_coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "peer_status_coordinator"

[dependencies]
hc_zome_peer_status_coordinator = { workspace = true }
