[workspace]
members = [
  "dnas/*/zomes/coordinator/*",
  "dnas/*/zomes/integrity/*",
  "crates/*",
  "src-tauri",
]
resolver = "2"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = { version = "0.3" }
hdk = { version = "0.2" }
serde = "1"
holochain = { version = "0.3.0-beta-dev.8" }
