[workspace]
resolver = "2"
members = [
  "dnas/sensemaker/zomes/coordinator/*",
  "dnas/sensemaker/zomes/integrity/*",
  "dnas/test_provider/zomes/coordinator/*",
  "dnas/test_provider/zomes/integrity/*",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = "0.1"
hdk = { version = "0.0.161" }
serde = "1"
holochain = {version = "0.0.173"}