[workspace]
members = [
  "dnas/*/zomes/coordinator/*",
  "dnas/*/zomes/integrity/*",
  "crates/*",
  "src-tauri",
]
resolver = "2"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = { version = "0.2.0" }
hdk = { version = "0.1.0" }
serde = "1"
holochain = { version = "0.1.3", features = ["db-encryption"] }
