[workspace]
members = [
  "dnas/lobby/zomes/membrane_invitations",
  "dnas/we/zomes/applets",
  "dnas/we/zomes/profiles",
  "dnas/we/zomes/we",
  "dnas/we/zomes/peer_status",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
