[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "we_coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "we_coordinator"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

we_integrity = { path = "../../integrity/we"}

[dev-dependencies]
futures = { workspace = true }
nanoid = { workspace = true }
observability = { workspace = true }
stream-cancel = { workspace = true }
tokio = { workspace = true }

