[package]
edition = "2021"
name = "sensemaker_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "sensemaker_integrity"

[dependencies]
serde = { workspace = true }
hdi = { workspace = true }
sensemaker_integrity_structs = { path = "../sensemaker_structs" }
