[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "we_integrity"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "we_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
thiserror = "1.0.20"
