
import neighbourhood from './sensemaker_dna/sensemaker/neighbourhood';
import sensemaker_community_activator from './sensemaker_dna/sensemaker/community_activator';
import sensemaker_config from './sensemaker_dna/sensemaker/sm_config';
import applet_config from './sensemaker_dna/sensemaker/applet_config';
import range from './sensemaker_dna/sensemaker/range';
import dashboard from './sensemaker_dna/sensemaker/dashboard';
import agent from './sensemaker_dna/sensemaker/agent';
import method from './sensemaker_dna/sensemaker/method';
import resource_def from './sensemaker_dna/sensemaker/resource_def';
import widget_config from './sensemaker_dna/widget/widget_config';
// range();
// neighbourhood();
// applet_config();
// sensemaker_config();
// sensemaker_community_activator();
// dashboard();
// agent();
// method();
resource_def();
// widget_config();
