[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "applets_integrity"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "applets_integrity"

[dependencies]
derive_more = "0.99"
serde = "1"
thiserror = "1.0.20"
chrono = { version = "=0.4.22", default-features = false, features = ["clock", "std", "oldtime", "serde"], optional = true }


hdi = "0.0.18"
