[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "applets_coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "applets_coordinator"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }

applets_integrity = { path = "../../integrity/applets" }

[dev-dependencies]
fixt = { workspace = true }
futures = { workspace = true }
hdk = { workspace = true }
holochain = { workspace = true }
tokio = { workspace = true }
