[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "applets_coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "applets_coordinator"

[dependencies]
derive_more = "0.99"
hdk = {version = "0.0.146", features = ["encoding"]}
serde = "1"
thiserror = "1.0.20"
chrono = { version = "=0.4.22", default-features = false, features = ["clock", "std", "oldtime", "serde"], optional = true }

applets_integrity = { path = "../../integrity/applets" }

[dev-dependencies]
fixt = "0.0.14"
futures = {version = "0.3.1", default-features = false}
hdk = {version = "0.0.146", features = ["encoding", "test_utils"]}
holochain = {version = "0.0.154", default-features = false, features = ["test_utils"]}
tokio = {version = "1.3", features = ["full"]}
