[package]
authors = ["guillem.cordoba@gmail.com"]
edition = "2021"
name = "hc_zome_attachments_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_attachments_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
