name: Merge to Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]

    name: Build styles
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build:styles

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/**/*.css
      - name: Merge Build Artifacts
        run: git config user.name "GitHub Actions"; git config user.email "actions@users.noreply.github.com"; git add -A; git commit -m "Update built styles"; git push; # Merge the latest commit from the workflow run
  
