name: "release"
on:
  push:
    branches:
      - release-happ

jobs:
  publish-happ:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      releaseId: ${{ steps.create-release.outputs.id }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v3

      - name: Extend space
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          extra_nix_config: |
            experimental-features = flakes nix-command

      - uses: cachix/cachix-action@v12
        with:
          name: holochain-ci

      - name: Install and test
        run: |
          nix-store --gc
          nix develop --command bash -c "npm i && npm run build:happ"

      - name: Retrieve version
        run: |
          echo "APP_VERSION=$(cat src-tauri/tauri.conf.json | grep -oP '(?<="version": ")[^"]*')" >> $GITHUB_OUTPUT
        id: version

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "workdir/we.happ"
          body: "See assets below to download and install this version."
          name: We happ v${{ steps.version.outputs.APP_VERSION }}-holochain-0.2.3-beta-rc.1
          tag: we-alpha-happ-v${{ steps.version.outputs.APP_VERSION }}
          prerelease: true
          draft: true

